export const CHECK_REQUEST_REQUEST = "CHECK_REQUEST_REQUEST"
export const CHECK_REQUEST_SUCCESS = "CHECK_REQUEST_SUCCESS"
export const CHECK_REQUEST_FAILED = "CHECK_REQUEST_FAILED"

export const CONNECTION_REQUEST = "CONNECTION_REQUEST" 
export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS" 
export const CONNECTION_FAILED = "CONNECTION_FAILED" 

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT" 